### ISSUE TITLE
Double self-referential serializer causes "RecursionError: maximum recursion depth exceeded" in v1.9.6

### ISSUE THREAD

**Issue by ses4j** [AltSchool/dynamic-rest#295]
I just started seeing a pair of self-referential serializers causing infinite recursion during a PUT when I upgraded to dynamic-rest v1.9.6.

```
class MyTransaction(DynamicModelSerializer):
    ...
    previous_transaction_id = DynamicRelationField(
        'MyTransaction', source='previous_transaction', read_only=True
    )
    previous_transaction = DynamicRelationField(
        'MyTransaction', embed=True, deferred=True, read_only=True
    )
```

In v1.9.4 and v1.9.5 this does not cause infinite recursion.  In v1.9.6 it does.

If I comment out EITHER of those two or BOTH, it does not cause infinite recursion.  Only when both are there does it crash.

Recursion loop here:

```
Traceback (most recent call last):
  File "...\site-packages\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "...\site-packages\dynamic_rest\viewsets.py", line 587, in update
    **kwargs)
  File "...\site-packages\rest_framework\mixins.py", line 67, in update
    instance = self.get_object()
  File "...\site-packages\rest_framework\generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "...\site-packages\rest_framework\generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "...\site-packages\dynamic_rest\filters.py", line 203, in filter_queryset
    disable_prefetches=disable_prefetches,
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
  File "...\site-packages\dynamic_rest\filters.py", line 425, in _build_requested_prefetches
    requirements=required
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
  File "...\site-packages\dynamic_rest\filters.py", line 425, in _build_requested_prefetches
    requirements=required
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
  File "...\site-packages\dynamic_rest\filters.py", line 425, in _build_requested_prefetches
    requirements=required
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
  File "...\site-packages\dynamic_rest\filters.py", line 425, in _build_requested_prefetches
    requirements=required
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
  File "...\site-packages\dynamic_rest\filters.py", line 425, in _build_requested_prefetches
    requirements=required
  File "...\site-packages\dynamic_rest\filters.py", line 542, in _build_queryset
    filters
....
```

**Comment by ses4j** [comment]
If we remove (from https://github.com/AltSchool/dynamic-rest/commit/26ee4b507becbc93644d69a5480ea1d903fb474e):

```
        # Implicit requirements (i.e. via `requires`) can potentially
        # include fields that haven't been explicitly included.
        # Such fields would not be in `fields`, so they need to be added.
        implicitly_included = set(requirements.keys()) - set(fields.keys())
        if implicitly_included:
            all_fields = serializer.get_all_fields()
            fields.update({
                field: all_fields[field]
                for field in implicitly_included
                if field in all_fields
            })
```

then the recursion problem goes away.
